---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-deployments
  namespace: arc-runners
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-create-deployments
  namespace: arc-runners
subjects:
  - kind: ServiceAccount
    name: arc-runner-set-gha-rs-no-permission
    namespace: arc-runners
roleRef:
  kind: Role
  name: create-deployments
  apiGroup: rbac.authorization.k8s.io