apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-on-additional-node
  labels:
    app: app-on-additional-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-on-additional-node
  template:
    metadata:
      labels:
        app: app-on-additional-node
    spec:
      nodeSelector:
        billing-team: my-team
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi