apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: system
spec:
  # Required fields
  role: "cn-practice-eks-node-role"

  subnetSelectorTerms:
    - id: "subnet-0ec9c385b3b4b1176"

  securityGroupSelectorTerms:
    - id: "sg-016c503830b78a517"

  ephemeralStorage:
    size: "10Gi"    # Range: 1-59000Gi or 1-64000G or 1-58Ti or 1-64T
    iops: 3000      # Range: 3000-16000
    throughput: 125 # Range: 125-1000
    # Optional KMS key for encryption
    kmsKeyID: "arn:aws:kms:ap-northeast-2:456247443832:alias/cn-practice-ebs-encryption"