extraEnv:
  - name: AWS_REGION
    value: "ap-northeast-2"

config:
  applicationsAPIKind: "kubernetes"
  logLevel: "debug"

  registries:
  - name: ECR
    api_url: https://456247443832.dkr.ecr.ap-northeast-2.amazonaws.com
    prefix: 456247443832.dkr.ecr.ap-northeast-2.amazonaws.com
    default: true
    ping: yes
    insecure: no
    credentials: ext:/scripts/ecr-login.sh
    credsexpire: 10h
 
authScripts:
  enabled: true
  scripts:
    ecr-login.sh: |
      #!/bin/sh
      echo "AWS:$(aws ecr get-login-password --region $AWS_REGION)"

securityContext:
  readOnlyRootFilesystem: false