issues:
  - title: Terraformバックエンドを作成する
    body: |
      Terraformのtfstateを保存するためのバックエンドを作成する**tfbackend**モジュールを作成する。
      
      # コードの場所
      `codes`ディレクトリ配下に`tfbackend`ディレクトリを作成し、そこにコードを配置する。
      
      # 欲しいもの
      - S3バケット(state格納用)
        - バージョニングを有効
      - DynamoDB(排他制御用)
      
      # その他
      バックエンドを作成するコード自体は初めリモートバックエンドの設定をせずにリソース群をデプロイします。
      S3とDynamoDBをデプロイしたらリモートバックエンドの設定を行い、tfstateをリモートバックエンドに格納します。

      参考:[s3](https://developer.hashicorp.com/terraform/language/backend/s3)
  - title: ネットワークを作成する
    body: |
      VPCをおよびサブネットを作成する**network**モジュールを作成する。
      
      # コードの場所
      `codes`ディレクトリ配下に`network`ディレクトリを作成し、そこにコードを配置する。
      
      # 欲しいもの
      - VPC
        - CIDRは任意
        - DNSホスト名を有効
        - DNS解決を有効
      - サブネット
        - AZ3つに分散
        - 各AZにプライベートサブネットとパブリックサブネットを作る
        - CIDRは任意
        - パブリックサブネットはインターネットゲートウェイに接続
        - パブリックサブネットにはNATゲートウェイを作成
          - 費用削減のためNATゲートウェイは1つのみ
          - NATゲートウェイはElastic IPを持つ
      - ルートテーブル
        - パブリックサブネット: インターネットゲートウェイ
        - プライベートサブネット: NATゲートウェイ
      - 出力値
        - VPC ID
        - 各サブネット ID
          - パブリック・プライベートごとにリスト型で出力

