# issue_settings.yaml
# 各スクリプトのパラメータをここで管理
settings:
  - name: container
    label:
      name: コンテナ
      color: C5DEF5
      description: コンテナの設定
    issue_yaml: container.yaml
  - name: configuration
    label:
      name: 構成管理
      color: 1f77b4
      description: インフラや設定の管理
    issue_yaml: configuration.yaml
  - name: cicd
    label:
      name: CI/CD
      color: f9d0c4
      description: インフラや設定の管理
    issue_yaml: cicd.yaml
  - name: o11y
    label:
      name: オブザーバビリティ
      color: 7b00a8
      description: インフラや設定の管理
    issue_yaml: o11y.yaml
  - name: availability
    label:
      name: 可用性
      color: c0fed0
      description: インフラや設定の管理
    issue_yaml: availability.yaml