issues:
  - title: EKSクラスタエンドポイントのアクセス制御
    body: |
      EKSクラスタのAPIサーバーへのアクセスを制御することで、セキュリティを向上させることができます。EKSクラスタのエンドポイントには、プライベートエンドポイントとパブリックエンドポイントがあり、それぞれ異なる特性を持ちます。

      ## エンドポイントの種類

      ### パブリックエンドポイント（デフォルト）
      - インターネット経由でAPIサーバーにアクセス可能
      - パブリックIPアドレスが割り当てられる
      - EKSの設定でアクセス可能なCIDRブロックを指定可能

      ### プライベートエンドポイント
      - VPC内からのみAPIサーバーにアクセス可能
      - プライベートIPアドレスが割り当てられる
      - クラスタのセキュリティグループでアクセス制御が可能

      ### パブリック + プライベート（混合モード）
      - 両方のエンドポイントが有効
      - 柔軟なアクセス制御が可能
      - 段階的な移行に適している

      ## セキュリティ上の考慮事項

      ### パブリックエンドポイントの場合
      - 必ずCIDRブロックでアクセス制限を設定する
      - 自組織のパブリックIPアドレスのみ許可
      - 0.0.0.0/0（全開放）は避ける

      ### プライベートエンドポイントの場合
      - VPC内にENI（Elastic Network Interface）が作成される
      - ノードからクラスターへの通信がVPC内で完結
      - ENIにはEKSクラスタのセキュリティグループが適用される

      ## 運用上の注意点

      ### パブリックエンドポイント使用時
      - CI/CDパイプラインからのアクセスが容易
      - 外部からの管理操作が可能

      ### プライベートエンドポイント使用時
      - CI/CDはVPC内リソースからの実行が必要
      - VPC内のbastion hostやVPN接続でアクセス可能

      ## 設定の移行

      プライベートからパブリック、またはその逆への変更は可能ですが、以下の点に注意：
      - CI/CDパイプラインの設定変更が必要
      - DNS解決の動作が変更される

      # プラクティス
      - EKSクラスタのエンドポイント設定を確認・変更する
        - 作業端末がEKSと同じネットワークの場合
          - EKSのパブリックエンドポイントを無効にする
          - クラスタのセキュリティグループに作業端末のIPアドレスを追加
        - 作業端末がEKS外部のネットワークの場合
          - EKSのパブリックエンドポイントを有効にする
          - エンドポイントのアクセス制限で作業端末のIPアドレスを許可する

  - title: EKSアクセスエントリーによる認証・認可の管理
    body: |
      EKSアクセスエントリー（Access Entry）は、EKSクラスタへのアクセス管理を効率化する機能です。従来のaws-authConfigMapに代わる新しいアクセス管理手法として、より安全で管理しやすい方法を提供します。

      [EKS アクセスエントリを使用して Kubernetes へのアクセスを IAM ユーザーに許可する](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/access-entries.html)

      ## アクセスエントリーの概要

      ### 従来の課題（aws-auth ConfigMap）
      - ConfigMapの直接編集が必要で運用が複雑
      - 設定ミスによるクラスタアクセス喪失のリスク
      - IAMユーザー/ロールとKubernetesユーザーのマッピングが不透明

      ### アクセスエントリーの利点
      - AWS APIを通じた管理で運用が簡素化
      - IAMロール/ユーザーとKubernetes権限の明確な関連付け
      - Terraformなどのインフラコードでの管理が容易
      - 設定変更時のクラスタアクセス喪失リスクの軽減

      ## アクセスエントリーの種類

      ### 標準アクセスエントリー
      - IAMプリンシパル（ユーザー/ロール）を直接マッピング
      - Kubernetesグループへの所属を定義
      - カスタムポリシーやクラスタポリシーを適用可能

      ### EKS管理ポリシー
      AWSが提供する定義済みポリシー：
      - `AmazonEKSClusterAdminPolicy` - クラスタ管理者権限
      - `AmazonEKSAdminPolicy` - 標準管理者権限
      - `AmazonEKSEditPolicy` - リソース編集権限
      - `AmazonEKSViewPolicy` - 読み取り専用権限

      ## セキュリティのベストプラクティス

      ### 最小権限の原則
      - ユーザー/ロールに必要最小限の権限のみ付与
      - 開発・ステージング・本番環境で権限を分離
      - 一時的なアクセスには期限付きロールを使用

      ### ロールベースの管理
      - 個人ユーザーではなくIAMロールを使用
      - 部署・チーム単位でのロール分割
      - 外部IDプロバイダーとの連携（OIDC/SAML）

      # プラクティス
      - EKSクラスタにアクセスエントリーを設定するTerraformコードを作成する
        - 任意の追加のIAMユーザー/ロールのアクセスエントリーを作成する
        - 上記アクセスエントリーに任意のポリシーを適用する

  - title: EKSクラスタの監査ログ有効化
    body: |
      EKSクラスタの監査ログ（Audit Log）を有効化することで、クラスタでの全てのAPI操作を記録し、セキュリティインシデントの調査や法令遵守（コンプライアンス）に役立てることができます。

      [Amazon EKS コントロールプレーンのログ記録](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/control-plane-logs.html)

      ## 監査ログの概要

      ### EKSで有効化できるログタイプ
      - **api** - Kubernetes API サーバーのログ
      - **audit** - Kubernetes 監査ログ（重要）
      - **authenticator** - AWS IAM Authenticator のログ
      - **controllerManager** - Kubernetes コントローラーマネージャーのログ
      - **scheduler** - Kubernetes スケジューラーのログ

      ### 監査ログの重要性
      - すべてのKubernetes APIへのリクエストを記録
      - 誰が、いつ、何を実行したかを追跡可能
      - セキュリティインシデントの調査に必要
      - コンプライアンス要件の遵守に必要

      ## 監査ログで記録される情報

      ### リクエスト情報
      - APIエンドポイント（例：/api/v1/pods）
      - HTTPメソッド（GET、POST、PUT、DELETE）
      - リクエスト元のユーザー情報
      - リクエスト時刻とレスポンス時刻

      ### 認証・認可情報
      - IAMユーザー/ロール情報
      - Kubernetesユーザー/グループ情報
      - 認可の成功/失敗状況

      ### リソース操作情報
      - 操作対象のKubernetesリソース
      - 作成・変更・削除されたオブジェクトの詳細
      - リクエスト結果（成功・失敗）

      ## CloudWatch Logsでの監査ログ分析

      ### ログストリーム構成
      監査ログは以下の形式でCloudWatchログストリームに出力されます。EKSはロググループがない場合、自動で作成します。ただし、自動で作成するロググループは有効期限が設定されていないため、手動で作成することを推奨します。
      ```
      /aws/eks/<cluster-name>/cluster
      ```

      # プラクティス
      - eksモジュールを拡張する
        - EKSクラスタのログを出力するCloudWatch Logsのロググループを作成する
          - 任意の有効期限を設定する
        - EKSクラスタで監査ログを有効化する
          - cluster loggingの設定し監査ログ（audit）を出力させる
          - (監査ログ以外も任意で有効にして良い)

      # 更に発展的なプラクティス
      このプラクティスは余裕がなければやらなくてもいいです。

      - EKSクラスタの監査ログをS3バケットに出力する
        - CloudWatch LogsからS3バケットへのエクスポートを設定する
      - S3の監査ログの分析をAthenaで行う

  - title: Kubernetes NetworkPolicyによるネットワークセキュリティ
    body: |
      Kubernetes NetworkPolicyは、Pod間の通信を制御するセキュリティ機能です。デフォルトでは、すべてのPod間通信が許可されているため、NetworkPolicyを使用してネットワークレベルでのセグメンテーションを実装することで、セキュリティを大幅に向上させることができます。

      [ネットワークポリシー](https://kubernetes.io/ja/docs/concepts/services-networking/network-policies/)

      ## NetworkPolicyの概要

      ### デフォルトの動作
      - Kubernetesクラスタでは、すべてのPod間通信がデフォルトで許可
      - 異なるNamespace間でも自由に通信可能
      - セキュリティリスクが高い状態

      ### NetworkPolicyによる制御
      - Pod間の通信を明示的に制御
      - 送信（Egress）と受信（Ingress）トラフィックの制御
      - ラベルセレクターによる柔軟な対象選択

      ## NetworkPolicyの基本概念

      ### ポリシータイプ
      - **Ingress** - Podへの着信通信を制御
      - **Egress** - Podからの発信通信を制御
      - 両方を組み合わせて使用可能

      ### セレクター
      - **podSelector** - 対象となるPodを選択
      - **namespaceSelector** - 対象となるNamespaceを選択
      - **ipBlock** - CIDR範囲でのIP制御

      ## EKSでのPodの通信制御

      EKSでは従来より Security Groups for Pods を使用してPodの通信を制御することができました。[セキュリティグループを個別の Pod に割り当てる](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/security-groups-for-pods.html)

      しかし、EKS Auto Modeではサポートされていません。[EKS 自動モードl での VPC ネットワーキングとロードバランシングの説明](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/auto-networking.html)

      代わりに EKS Auto Mode では Networkpolicy がサポートされています。[EKS Auto Mode でネットワークポリシーを使用する](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/auto-net-pol.html)

      # プラクティス
      - ネットワークポリシーコントローラーを有効にするConfigMapを作成する
        - コードは`eks/k8s`ディレクトリに格納
      - NetworkPolicyを使用したセキュリティ制御の実装
        - frontend はVPCのCIDRからのみアクセスを許可
        - backend は frontend からのみアクセスを許可

  - title: EKSのSecurity Groups for Podsによるセキュリティ制御
    body: |
      **本issueは内容を確認するだけでクローズしてください。**

      Security Groups for Podsは、AWS EKSにおいてPodレベルでネットワークセキュリティを制御する機能です。

      [セキュリティグループを個別の Pod に割り当てる](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/security-groups-for-pods.html)

      ## Security Groups for Podsの概要

      ### 従来の課題
      - Kubernetesのデフォルトでは、すべてのPod間通信が許可
      - ネットワークレベルでのセグメンテーションが困難
      - 細かなアクセス制御ができない

      ### Security Groups for Podsの利点
      - AWS Security Groupsの機能をPodレベルで適用
      - IPアドレス、ポート、プロトコルレベルでの制御
      - AWS VPCネットワーキングとの統合
      - 既存のAWSセキュリティ管理プロセスとの一貫性

      ### 注意
      - VPC CNIプラグインが必要
      - サポートされるEC2インスタンスタイプに制限があります。（`t`ファミリーはサポートされません）
      - EKS Auto Modeではサポートされていません

      ## Security Groupsの適用方法

      - VPC CNI(aws-node)に`ENABLE_POD_ENI=true`の環境変数を設定。[Amazon EKS Pod のセキュリティグループ用に Amazon VPC CNI Plugin for Kubernetes を設定する](https://docs.aws.amazon.com/ja_jp/eks/latest/userguide/security-groups-pods-deployment.html)
      - Pod用にセキュリティグループを作成します。
      - SecurityGroupPolicyリソースを作成し、Podに適用するセキュリティグループを指定します。
        - SecurityGroupPolicyリソースとPodを同時に作成するとPod起動に失敗する可能性があります。その時はPodを再作成すれば起動できます。

      # プラクティス
      本プラクティスでは EKS Auto Mode のため、Security Groups for Podsは使用できません。

  - title: Kubernetes RBACによるアクセス制御
    body: |
      Kubernetes RBAC（Role-Based Access Control）は、クラスタ内のK8sリソースへのアクセスを制御するセキュリティ機能です。ユーザーやサービスアカウントに対して、必要最小限の権限のみを付与することで、セキュリティリスクを最小化できます。

      [Using RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac/)

      ## RBACの基本概念

      ### 主要なリソース
      - **Role** - Namespace内のリソースに対する権限を定義
      - **ClusterRole** - クラスタ全体のリソースに対する権限を定義
      - **RoleBinding** - RoleをユーザーやServiceAccountに紐付け
      - **ClusterRoleBinding** - ClusterRoleをユーザーやServiceAccountに紐付け

      ### APIGroups とリソースの指定
      
      RBACでは、対象となるKubernetesリソースをAPIGroupsとリソース名で指定します。主要なAPIGroupsは以下の通りです。

      - **""** (core group) - Pod、Service、ConfigMap、Secret など
      - **apps** - Deployment、DaemonSet、ReplicaSet など
      - **networking.k8s.io** - NetworkPolicy、Ingress など
      - **rbac.authorization.k8s.io** - Role、RoleBinding など
      - **apiextensions.k8s.io** - CustomResourceDefinition など

      利用可能なAPIGroupsとリソースは以下のコマンドで確認できます：
      ```bash
      # 全てのAPIリソースを表示
      kubectl api-resources
      ```

      ### ロールで設定する権限(verbs)の種類

      - **get** - リソースの取得
      - **list** - リソースの一覧表示
      - **create** - リソースの作成
      - **update/patch** - リソースの更新
      - **delete** - リソースの削除
      - **watch** - リソースの変更監視

      ## セキュリティのベストプラクティス

      ### 最小権限の原則
      - 必要な権限のみを付与
      - ワイルドカード（`*`）の使用を避ける

      ### ServiceAccountの管理
      - 用途別のServiceAccount作成
      - 不要なServiceAccountの削除

      # プラクティス

      時間による計画的な性能拡張を想定したCronJobを作成する。

      - CronJobを作成する
        - コードはcodes/frontend/k8sディレクトリに格納
        - スケールアウト用のCronJob
          - 時間は任意（スケールイン用の少なくとも2分前にする）
          - イメージは`bitnami/kubectl:latest`を使う
          - `kubectl patch deploy frontend -p '{"spec":{"replicas":3}}'`コマンドでフロントエンドのPod数を増やす
          - 任意のServiceAccountを指定
        - スケールイン用のCronJob
          - 基本的にスケールアウト用と同じ。時間とスケール数を変える
        - CronJob用のRBAC
          - ServiceAccount
          - Role
            - apps.deploymentsを"get", "list", "patch"する権限を持つ
          - RoleBinding

  - title: ReadOnlyRootFilesystemによるセキュリティ強化
    body: |
      ReadOnlyRootFilesystem設定は、コンテナのルートファイルシステムを読み取り専用にするセキュリティ機能です。この設定により、悪意のあるコードによるファイルシステムの改ざんやマルウェアの永続化を防止できます。

      [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)

      ## ReadOnlyRootFilesystemの概要

      ### セキュリティ上の利点
      - ファイルシステムへの不正な書き込みを防止
      - マルウェアの永続化を阻止
      - 実行時のファイル改ざんを防止
      - アプリケーションの不正な設定変更を阻止

      ### 動作原理
      - コンテナのルートファイルシステム（/）を読み取り専用でマウント
      - /tmp、/var/tmp などの一時ディレクトリも読み取り専用になる
      - 書き込みが必要な場合は、別途ボリュームをマウントする必要がある

      ## 実装時の考慮点

      ### 一時ファイルの処理
      多くのアプリケーションは一時ファイルを作成する必要があります：
      - `/tmp` ディレクトリへの書き込み
      - ログファイルの出力
      - 設定ファイルの動的生成

      ### 解決策
      書き込みが必要な場合は、以下のボリュームタイプを使用：
      - **emptyDir** - Pod内で共有する一時領域
      - **tmpfs** - メモリベースの一時ファイルシステム
      - **PersistentVolume** - 永続化が必要なデータ

      # プラクティス
      - frontendとbackendにReadOnlyRootFilesystemを設定する
        - frontendは`/var/cache/nginx`と`/run`に書き込みが必要

  - title: 非rootユーザーでのPod実行によるセキュリティ強化
    body: |
      Podを非rootユーザーで実行することは、コンテナセキュリティの基本的なベストプラクティスです。rootユーザーでの実行は、セキュリティ侵害時の影響範囲を拡大させるリスクがあるため、必要最小限の権限で実行することが重要です。

      [Configure a Security Context for a Pod or Container](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)

      ## 非rootユーザー実行の概要

      ### セキュリティ上の利点
      - 権限昇格攻撃のリスクを軽減
      - システムファイルへの不正アクセスを防止
      - コンテナブレイクアウト時の影響範囲を制限
      - 最小権限の原則に従った実行環境の実現

      ### デフォルトの問題
      - 多くのコンテナイメージはrootユーザー（UID 0）で実行される
      - rootユーザーはシステム全体への強力な権限を持つ
      - セキュリティ侵害時の被害が拡大しやすい

      ## 実装方法

      ### SecurityContextの設定
      PodまたはContainerレベルでSecurityContextを設定：
      - **runAsNonRoot** - 非rootユーザーでの実行を強制
      - **runAsUser** - 実行するユーザーのUIDを指定
      - **runAsGroup** - 実行するグループのGIDを指定
      - **fsGroup** - ボリュームの所有グループを指定

      ## 実装時の考慮点

      - **ポート1024未満の使用** - 1024までは特権が必要なためアプリケーションを8080などの非特権ポートで実行
      - **ファイル権限** - fsGroupを使用してボリュームの権限を調整
      - **イメージの変更** - 非rootユーザーが無い場合はDockerfileでユーザーを作成・切り替え

      # プラクティス
      - frontendとbackendのPodを非root強制にし非rootで実行する
        - frontend
          - nginxイメージにはnginxユーザーおよびグループ(101:101)が既に存在します
          - ポートを80から8080に変更する
            - nginx.confをconfigmapにして/etc/nginx/nginx.confにマウント
            - nginx.confに書かれたリッスンポートを80から8080に変更
            - その他、k8sマニフェストもポート変更
        - backend
          - nodeイメージにはnodeユーザーおよびグループ(1000:1000)が既に存在します
