apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-app-pvc
  namespace: velero-sample
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: auto-ebs-sc