---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: frontend-scaleout
  namespace: default
spec:
  schedule: "28 2 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-sa
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl patch deploy frontend -p '{"spec":{"replicas":3}}'
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: frontend-scalein
  namespace: default
spec:
  schedule: "30 2 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-sa
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl patch deploy frontend -p '{"spec":{"replicas":1}}'
          restartPolicy: OnFailure
---
