name: Checkov Security Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  checkov:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./example/actions/terraform
          framework: terraform
          check: CUSTOM_*
          external_checks_dirs: ./example/checkov/
