name: Push to ECR

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'codes/frontend/app/**'
on:
  workflow_dispatch:  # 手動トリガー

jobs:
  build-and-push:
    runs-on: arc-runner-set
    env:
      AWS_REGION: ap-northeast-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: codes/frontend/app
          push: true
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/frontend:${{ github.sha }}