name: Push to ECR

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'codes/frontend/app/**'
on:
  workflow_dispatch:  # 手動トリガー

jobs:
  build-and-push:
    runs-on: arc-runner-set
    env:
      AWS_REGION: ap-northeast-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          REPOSITORY: frontend
          IMAGE_TAG: ${{ github.sha }}
        working-directory: codes/frontend/app
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG